# Cron file for App Engine
cron:
  # 0 0 * * * <path/to/the/project>/symfony/bin/console user:cron --env=prod
  - description: "Clears up non activated accounts and expired captcha whitelists"
    url: /cron/user-cron
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console twilio:price
  - description: "Fetch missing message prices on Twilio"
    url: /cron/twilio-price
    schedule: every 1 hours

  # * * * * * <path/to/the/project>/symfony/bin/console clear:campaign
  - description: "Automatically close inactive campaigns"
    url: /cron/clear-campaign
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console clear:media
  - description: "Remove expired medias"
    url: /cron/clear-media
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console clear:space
  - description: "Remove expired volunteer space sessions"
    url: /cron/clear-space
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console clear:expirable
  - description: "Remove expired expirable entities"
    url: /cron/clear-expirable
    schedule: every 24 hours

  # * * * * * <path/to/the/project>/symfony/bin/console report:communication
  - description: "Creates communication reports"
    url: /cron/report-communication
    schedule: every 24 hours
