services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Bundles\SandboxBundle\Controller\HomeController: ~

  Bundles\SandboxBundle\Controller\AnonymizeController:
    arguments:
      - '@Bundles\SandboxBundle\Manager\AnonymizeManager'

  Bundles\SandboxBundle\Controller\FakeSmsController:
    arguments:
      - '@Bundles\SandboxBundle\Manager\FakeSmsManager'
      - '@App\Manager\MessageManager'
      - '@App\Manager\VolunteerManager'

  Bundles\SandboxBundle\Controller\FakeCallController:
    arguments:
      - '@Bundles\SandboxBundle\Manager\FakeCallManager'
      - '@App\Provider\Call\CallProvider'
      - '@App\Manager\VolunteerManager'

  Bundles\SandboxBundle\Controller\FakeEmailController:
    arguments:
      - '@Bundles\SandboxBundle\Manager\FakeEmailManager'
      - '@App\Manager\VolunteerManager'

  Bundles\SandboxBundle\Controller\FixturesController:
    arguments:
      - '@Bundles\SandboxBundle\Manager\FixturesManager'
      - '@translator'

  Bundles\SandboxBundle\Controller\FakeStorageController:
    arguments:
      - '@kernel'

  Bundles\SandboxBundle\Controller\SpinnerController: ~

  Bundles\SandboxBundle\Controller\FakeMinutisController:
    arguments:
      - '@Bundles\SandboxBundle\Manager\FakeOperationManager'
      - '@Bundles\SandboxBundle\Manager\FakeOperationResourceManager'
