services:

  Bundles\PegassCrawlerBundle\Command\PegassFilesCommand:
    arguments:
      - '@Bundles\PegassCrawlerBundle\Manager\PegassManager'
      - '@twig'
    tags:
      - { name: console.command }

  Bundles\PegassCrawlerBundle\Command\PegassSearchCommand:
    arguments:
      - '@Bundles\PegassCrawlerBundle\Manager\PegassManager'
      - '@logger'
    tags:
      - { name: console.command }
