services:

  Bundles\PegassCrawlerBundle\Manager\PegassManager:
    arguments:
      - '@event_dispatcher'
      - '@Bundles\PegassCrawlerBundle\Repository\PegassRepository'
      - '@monolog.logger.slack'
      - '@logger'
