####################################################################################################################################
# Useful links:
#
# Timezones
# https://gist.github.com/stasius12/f95f2999fa351212991c43a5f067c78d
#
# Twilio custom phone numbers support
# https://support.twilio.com/hc/en-us/articles/223183068-Twilio-international-phone-number-availability-and-their-capabilities
#
# Twilio sender id support
# https://support.twilio.com/hc/en-us/articles/223133767-International-support-for-Alphanumeric-Sender-ID
#
# Twilio programming voice support
# https://www.twilio.com/voice/pricing/pm
####################################################################################################################################
parameters:
  phones:
    fr: # +33, France
      timezone: 'Europe/Paris'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_LONG_FR)%'
      outbound_sms_enabled: true
      outbound_sms_short: '%env(TWILIO_FROM_SHORT_FR)%'
      outbound_sms_long: '%env(TWILIO_FROM_LONG_FR)%'
      inbound_call_enabled: true
      inbound_call_number: '%env(TWILIO_FROM_LONG_FR)%'
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    gp: # +590, Guadeloupe
      timezone: 'America/Guadeloupe'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_LONG_GP)%'
      outbound_sms_enabled: true
      outbound_sms_short: '%env(TWILIO_SENDER_ID_FR)%'
      outbound_sms_long: ~
      inbound_call_enabled: true
      inbound_call_number: '%env(TWILIO_FROM_LONG_GP)%'
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    gf: # +594, Guyane Française
      timezone: 'America/Cayenne'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_TOLL_FR)%'
      outbound_sms_enabled: true
      outbound_sms_short: ~
      outbound_sms_long: '%env(TWILIO_FROM_LONG_FR)%'
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    mq: # +596, Martinique
      timezone: 'America/Martinique'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_LONG_MQ)%'
      outbound_sms_enabled: true
      outbound_sms_short: '%env(TWILIO_SENDER_ID_FR)%'
      outbound_sms_long: ~
      inbound_call_enabled: true
      inbound_call_number: '%env(TWILIO_FROM_LONG_MQ)%'
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    yt: # +262, Mayotte
      timezone: 'Indian/Mayotte'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_TOLL_FR)%'
      outbound_sms_enabled: true
      outbound_sms_short: '%env(TWILIO_SENDER_ID_FR)%'
      outbound_sms_long: ~
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    pf: # +689, Polynésie Française
      timezone: 'Pacific/Tahiti'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_TOLL_FR)%'
      outbound_sms_enabled: true
      outbound_sms_short: '%env(TWILIO_SENDER_ID_FR)%'
      outbound_sms_long: ~
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    re: # +262, Réunion
      timezone: 'Indian/Reunion'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_TOLL_FR)%'
      outbound_sms_enabled: true
      outbound_sms_short: '%env(TWILIO_SENDER_ID_FR)%'
      outbound_sms_long: ~
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    nc: # +687, Nouvelle-Calédonie
      timezone: 'Pacific/Noumea'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_TOLL_FR)%'
      outbound_sms_enabled: true
      outbound_sms_short: '%env(TWILIO_SENDER_ID_FR)%'
      outbound_sms_long: ~
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    pm: # +508, Saint-Pierre-et-Miquelon
      timezone: 'America/Miquelon'
      outbound_call_enabled: true
      outbound_call_number: '%env(TWILIO_FROM_TOLL_FR)%'
      outbound_sms_enabled: true
      outbound_sms_short: ~
      outbound_sms_long: '%env(TWILIO_FROM_LONG_FR)%'
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    bl: # +590, Saint-Barthélemy
      timezone: 'America/St_Barthelemy'
      outbound_call_enabled: false
      outbound_call_number: ~
      outbound_sms_enabled: true
      outbound_sms_short: ~
      outbound_sms_long: '%env(TWILIO_FROM_LONG_FR)%'
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    mf: # +590, Saint-Martin
      timezone: 'America/Marigot'
      outbound_call_enabled: false
      outbound_call_number: ~
      outbound_sms_enabled: true
      outbound_sms_short: ~
      outbound_sms_long: '%env(TWILIO_FROM_LONG_FR)%'
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
    wf: # +681, Wallis-et-Futuna
      timezone: 'Pacific/Wallis'
      outbound_call_enabled: false
      outbound_call_number: ~
      outbound_sms_enabled: true
      outbound_sms_short: ~
      outbound_sms_long: '%env(TWILIO_FROM_LONG_FR)%'
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: false
      platform: fr
      provider: twilio
#    es: # +34, Spain
#      timezone: 'Europe/Madrid'
#      outbound_call_enabled: true
#      outbound_call_number: '%env(TWILIO_FROM_LONG_ES)%'
#      outbound_sms_enabled: true
#      outbound_sms_short: ~
#      outbound_sms_long: '%env(TWILIO_FROM_LONG_ES)%'
#      inbound_call_enabled: true
#      inbound_call_number: '%env(TWILIO_FROM_LONG_ES)%'
#      inbound_sms_enabled: true
    pt: # +351, Portugal
      timezone: 'Europe/Lisbon'
      outbound_call_enabled: false
      outbound_call_number: '%env(TWILIO_FROM_LONG_ES)%'
      outbound_sms_enabled: true
      outbound_sms_short: ~
      outbound_sms_long: '%env(TWILIO_FROM_LONG_ES)%'
      inbound_call_enabled: false
      inbound_call_number: ~
      inbound_sms_enabled: true
      platform: pt
      provider: twilio
