api:
  resource: '@ApiBundle/Controller/'
  type: annotation

controllers:
  resource: ../../src/Controller/
  type: annotation

password_login:
  resource: '@PasswordLoginBundle/Controller/'
  type: annotation

twilio:
  resource: '@TwilioBundle/Controller/'
  type: annotation

google_task:
  resource: '@GoogleTaskBundle/Controller/'
  type: annotation

chart:
  resource: '@ChartBundle/Controller/'
  type: annotation

sandbox:
  resource: '@SandboxBundle/Controller/'
  type: annotation
  prefix: /sandbox
  name_prefix: sandbox_
