controllers:
  resource: ../../src/Controller/
  type: attribute

password_login:
  resource: '@PasswordLoginBundle/Controller/'
  type: attribute

twilio:
  resource: '@TwilioBundle/Controller/'
  type: attribute

google_task:
  resource: '@GoogleTaskBundle/Controller/'
  type: attribute
