security:

  password_hashers:
    App\Entity\User: bcrypt

  providers:
    user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: '^/'
      provider: user_provider
      lazy: true
      logout:
        path: /logout
        target: /
        enable_csrf: true
      custom_authenticators:
        - App\Security\Authenticator\MinutisAuthenticator
        - App\Security\Authenticator\GoogleConnectAuthenticator
        - Bundles\PasswordLoginBundle\Security\Authenticator\FormLoginAuthenticator
        - App\Security\Authenticator\NivolAuthenticator
      entry_point: App\Security\Authenticator\MinutisAuthenticator
      remember_me:
        token_provider:
          doctrine: true
        secret: '%kernel.secret%'

  role_hierarchy:
    ROLE_ROOT: ROLE_ADMIN

  access_control:

    # Technical
    - { path: '^/_ah', roles: PUBLIC_ACCESS }
    - { path: '^/cron', roles: PUBLIC_ACCESS }
    - { path: '^/task', roles: PUBLIC_ACCESS }
    - { path: '^/deploy', roles: PUBLIC_ACCESS }

    # Minutis authentication
    - { path: '^/auth$', roles: PUBLIC_ACCESS }

    # Google Connect
    - { path: '^/google-(connect|verify)$', roles: PUBLIC_ACCESS }

    # Volunteer space
    - { path: '^/space', roles: PUBLIC_ACCESS }

    # Webhooks (sms response received)
    - { path: '^/twilio', roles: PUBLIC_ACCESS }

    # Medias (generated voice calls)
    - { path: '^/media', roles: PUBLIC_ACCESS }

    # Unauthenticated identity management
    - { path: '^/connect', roles: PUBLIC_ACCESS }
    - { path: '^/register', roles: PUBLIC_ACCESS }
    - { path: '^/forgot-password', roles: PUBLIC_ACCESS }
    - { path: '^/change-password', roles: PUBLIC_ACCESS }
    - { path: '^/verify-email', roles: PUBLIC_ACCESS }
    - { path: '^/locale', roles: PUBLIC_ACCESS }
    - { path: '^/nivol', roles: PUBLIC_ACCESS }
    - { path: '^/code', roles: PUBLIC_ACCESS }

    # Links contained in SMS should be publicly available
    - { path: '^/syn', roles: PUBLIC_ACCESS }
    - { path: '^/msg', roles: PUBLIC_ACCESS }
    - { path: '^/geo', roles: PUBLIC_ACCESS }

    # We allow non activated users to reach a few pages
    - { path: '^/logout', roles: ROLE_USER }
    - { path: '^/profile', roles: ROLE_USER }
    - { path: '^/guest', roles: ROLE_USER }
    - { path: '^/$', roles: [ 'ROLE_USER' ] }

    # Website administration
    - { path: '^/admin', roles: [ 'ROLE_ADMIN' ] }

    # Google Cloud Tasks
    - { path: '^/cloud-task$', roles: PUBLIC_ACCESS }

    # Requires an activated account for other pages
    - { path: '^/', roles: [ 'ROLE_TRUSTED' ] }
