services:

  Bundles\ApiBundle\Controller\DemoController:
    calls: [ [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ] ]
    tags:
      - controller.service_arguments
      - container.service_subscriber

  Bundles\ApiBundle\Controller\TokenController:
    arguments:
      - '@Bundles\ApiBundle\Manager\TokenManager'
      - '@Bundles\ApiBundle\Reader\CategoryCollectionReader'
      - '@Bundles\ApiBundle\Reader\FacadeReader'
    calls: [ [ 'setContainer', [ '@Psr\Container\ContainerInterface' ] ] ]
    tags:
      - controller.service_arguments
      - container.service_subscriber
