services:

  Bundles\ApiBundle\Listener\ViewListener:
    arguments:
      - '@serializer'
      - '@Bundles\ApiBundle\Reader\StatusCodeReader'
    tags:
      - { name: kernel.event_listener, event: kernel.view }

  Bundles\ApiBundle\Listener\ExceptionListener:
    arguments:
      - '@serializer'
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  Bundles\ApiBundle\Listener\RequestListener:
    arguments:
      - '@translator'
    tags:
      - { name: kernel.event_listener, event: kernel.request }
