steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/cloudrun/Dockerfile
      - --build-arg
      - ENV=${_ENV}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s
