monolog:
  channels:
    - default
    - slack

  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_404s:
        # regex: exclude all 404 errors from the logs
        - ^/
    nested:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine" ]
    google_cloud_no_info:
      type: fingers_crossed
      handler: google_cloud
      action_level: warning
    google_cloud:
      type: service
      id: monolog_psr_batch_logger
      level: warning
    slack_no_404:
      type: fingers_crossed
      handler: slack_errors
      action_level: error
      excluded_http_codes: [ 400, 401, 403, 404 ]
    slack_errors:
      type: slack
      token: '%env(SLACK_TOKEN)%'
      channel: '%env(SLACK_CHANNEL)%'
      level: 'ERROR'
      include_extra: true
    slack:
      type: slack
      token: '%env(SLACK_TOKEN)%'
      channel: '%env(SLACK_CHANNEL)%'
      channels: [ 'slack' ]

services:

  monolog_psr_batch_logger:
    class: Monolog\Handler\PsrHandler
    arguments: [ '@google_cloud_stackdriver_psr_batch_logger' ]

  google_cloud_stackdriver_psr_batch_logger:
    class: Google\Cloud\Logging\PsrLogger
    factory: [ 'Google\Cloud\Logging\LoggingClient', 'psrBatchLogger' ]
    arguments: [ 'app' ]
